### ISSUE TITLE
ネットワーク構成を考える

### ISSUE THREAD

**Issue by sorah** [kosendj/ops#2]
おもしろくシンプルにやります
## 方針
- 箱に持ち込むのはシンプルに
  - とりあえずルータ代わりのマシン・スイッチ・アプリ用のマシンの 3 つ、あとケーブル類
  - ルータ代わりのマシンとアプリ用のマシンは一個にしたいけどわたし手持ちの機材だと厳しい
  - (余ってるラップトップあったらほげしてください)
- 箱のネットワークがどうなってるか詳細まったくわからんけど NAT テーブルとかの事を考えて全部 VPN でインターネットに流せるようにもしておく
  - どっちでも対応できるように
  - どちらにしろ VPC との繋ぎ込みは VPN でやっていいかなとか思ってる
- VPN はたやすく抜けられるであろう OpenVPN で
  - PSK にするか TLS base にするか悩むけどパフォーマンス次第だなあ
## subnet
- 172.18.0.0/15
  - vpc ap-northeast-1 172.18.0.0/16 (vpc.ops.kosendj-bu.in)
    - az1 172.18.0.0/18
      - az1-public 172.18.0.0/20
      - az1-private 172.18.16.0/20
    - az2 172.18.64.0/18
      - az2-public 172.18.64.0/20
      - az2-private 172.18.80.0/20
  - box 172.19.0.0/16 (box.ops.kosendj-bu.in)
    - management 172.19.224.0/19 vlan=0
    - servers 172.19.128.0/19 vlan=100
    - clients 172.19.0.0/19 vlan=200

(利用 AZ 未確定だけど最大でも 2 AZ くらいで subnet 切れるようにしとけば十分なので az1, az2 と表記)
### 本番時
- vpc
  - router
    - openvpn
    - unbound
  - camo + nginx proxy_cache
  - gj
  - 画像管理する奴?
- box
  - router
    - openvpn
    - dnsmasq
  - app
    - gj (mirror)
    - 画像管理する奴? (mirror)
    - gif ストレージのミラー
    - nginx proxy_cache → camo
  
  各アプリの縮退先はこれから考えます。ていうか gif 管理する奴そろそろ作らないといけない

**Comment by sorah** [comment]
とりあえずaws vpc, subnet, routes はつくった

**Comment by sorah** [comment]
X60 retoree.box.ops.kosendj-bu.in 172.19.224.1 (172.19.128.1, 172.19.0.1)
MBA11" cyan.box.ops.kosendj-bu.in 172.19.128.10

**Comment by asonas** [comment]
SHOW BY ROCK is kool...

**Comment by sorah** [comment]
maple.pub.ops.kosendj-bu.in

**Comment by sorah** [comment]
GS105Ev2 moa.box.ops.kosendj-bu.in 172.19.224.2
WG1800HP chuchu.box.ops.kosendj-bu.in 172.19.224.3

**Comment by sorah** [comment]
![](http://i.gyazo.com/b177b9d27d52962d150f1ef82919c06d.png)

![](http://i.gyazo.com/1a2d11ec1790b430ae8022316e08aaeb.png)
